### ISSUE TITLE
Kompas in plaats van reddingsboei

### ISSUE THREAD

**Issue by Colin-TUE** [Brutusn/Tracker#23]
In plaats van een reddingsboei als standaard item een kompas laten zien. Dat zou mooi zijn voor tijdens het kompas deel en is er geen extra app nodig.

@Brutusn: Moeten bepalen of dit een Must have of een Nice to have is. Afhankelijk van het antwoord, kijken of dit af kan voordat we het laatste deel opnieuw uitzetten/testen.

**Comment by Brutusn** [comment]
Ik zie het meer als nice to have. (ik wil graag alle nice to haves ook hebben hoor.)

Wanneer wil je het laatste deel uitzetten/testen?

**Comment by Colin-TUE** [comment]
Getest tijdens het laatste deel opnieuw uitzetten. Volgende verbeteringen gewenst:
- Refresh rate is niet zo hoog en zou vaker mogen. Tijdens het rijden was het best aardig up-to-date, maar tijdens het stil staan op een kruispunt niet altijd. 
- Het zou erg helpen als de letters van de windroos erbij staan. Dit is vooral handig voor het snel kunnen bepalen welke kant je op moet op een kruising.

**Comment by Brutusn** [comment]
Refresh rate kan ik niets aan doen. Die staat zo snel die kan. (1 keer per seconde..) is een default van de browser zelf. Het compas kan ik helaas niet direct aanspreken (zou wel mooi zijn)

De letters ga ik wel toevoegen!
